package com.ringpublishing.gdpr;

public enum RingPublishingGDPRError
{
    ERROR_EMPTY_CONSENT_FORM_LISTER,
    ERROR_REQUESTS_STATE_FAILURE,
    ERROR_MISSING_TENANT_CONFIGURATION,
    ERROR_CANNOT_FETCH_CONFIGURATION,
    ERROR_EMPTY_CONSENTS,
    ERROR_CANNOT_VERIFY_CONSENTS,
    ERROR_WEBVIEW_LOADING_FAIL,
    ERROR_WEBVIEW_MISSING_HOST,
}
